version: '3.7'

services:
  proxy:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:80
    # volumes:
    #   -
    networks:
      - network
    restart: always

networks:
  network:
    driver: bridge