version: '3.7'

services:
  proxy:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:80
    volumes:
      - config:/usr/local/nginx/conf
    networks:
      - network
    restart: always

volumes:
  config:

networks:
  network:
    driver: bridge